business_context:
  description: Direct to consumer business selling computer electronics devices and accessories
  key_concepts:
  - Orders ship on the same day as the order date
  - Retention is defined as a customer who purchased in the past 0-12 months and also had a purchase previous to that 0-12 month period
database_config:
  type: sqlite
  date_functions:
    year: strftime('%Y', {column})
    month: strftime('%Y-%m', {column})
    date: strftime('%Y-%m-%d', {column})
  date_formats:
    literal: YYYY-MM-DD
    year: YYYY
    month: YYYY-MM
  example_patterns:
  - description: Monthly aggregation
    pattern: strftime('%Y-%m', {column}) AS {alias}
  - description: Year comparison
    pattern: strftime('%Y', {column}) = '{year}'
  - description: Date range
    pattern: '{column} BETWEEN ''{start_date}'' AND ''{end_date}'''
tables:
  customers:
    description: Table containing customers data
    fields:
      id:
        type: INTEGER
        description: id field
        is_key: true
      name:
        type: TEXT
        description: name field
      email:
        type: TEXT
        description: email field
      phone:
        type: TEXT
        description: phone field
      address:
        type: TEXT
        description: address field
      city:
        type: TEXT
        description: city field
      state:
        type: TEXT
        description: state field
      country:
        type: TEXT
        description: country field
      created_at:
        type: TIMESTAMP
        description: created_at field
  sqlite_sequence:
    description: Table containing sqlite_sequence data
    fields:
      name:
        type: ''
        description: name field
      seq:
        type: ''
        description: seq field
  orders:
    description: Table containing orders data
    fields:
      id:
        type: INTEGER
        description: id field
        is_key: true
      customer_id:
        type: INTEGER
        description: customer_id field
        foreign_key: customers.id
      product_name:
        type: TEXT
        description: product_name field
      category:
        type: TEXT
        description: product category
      quantity:
        type: INTEGER
        description: number of items in the order
      price:
        type: REAL
        description: item price field
      total_price:
        type: REAL
        description: total amount of the order
      payment_method:
        type: TEXT
        description: payment_method field
      order_date:
        type: TIMESTAMP
        description: is both the order and shipped date
      delivery_date:
        type: TIMESTAMP
        description: delivery_date field
    relationships:
    - table: customers
      type: many_to_one
      join_fields:
      - customer_id
      - id
query_guidelines:
  tips:
  - Use proper table aliases in joins
  - Include appropriate WHERE clauses
  - Use proper date formatting for timestamp columns
  - Consider using aggregation functions where appropriate
  validation:
  - Ensure column references are fully qualified (table.column)
  - Include proper type casting for numerical operations
  - Use COALESCE for handling NULL values in calculations
