business_context:
  description: Enhanced schema configuration for Snowflake TPC-H data with more business context
  key_concepts:
  - TPC-H represents a global wholesale supplier's business operations
  - Orders flow from customers through suppliers across different regions
  - Key metrics include order values, shipping times, and supplier performance
  - Market segments and customer demographics drive business decisions
database_config:
  type: snowflake
  date_functions:
    year: DATE_PART('YEAR', {column})
    month: DATE_TRUNC('MONTH', {column})
    date: DATE_TRUNC('DAY', {column})
  query_guidelines:
    tips:
    - Prefer joins that follow the natural business flow (customer → orders → lineitems)
    - Consider market segments when analyzing customer behavior
    - Account for shipping dates and receipt dates in delivery analysis
tables:
  CUSTOMER:
    description: Represents our global customer base across different market segments and regions
    fields:
      C_CUSTKEY:
        type: NUMBER
        description: Primary identifier for each customer account
        nullable: false
        is_key: true
      C_NAME:
        type: TEXT
        description: Customer's registered business name
        nullable: false
      C_ADDRESS:
        type: TEXT
        description: Primary business address
        nullable: false
      C_NATIONKEY:
        type: NUMBER
        description: Links to customer's home nation, important for regional analysis
        nullable: false
        foreign_key: NATION.N_NATIONKEY
      C_PHONE:
        type: TEXT
        description: Primary contact number
        nullable: false
      C_ACCTBAL:
        type: NUMBER
        description: Current account balance in standard currency units
        nullable: false
      C_MKTSEGMENT:
        type: TEXT
        description: Customer's primary market segment (e.g., AUTOMOBILE, BUILDING, FURNITURE)
        nullable: true
      C_COMMENT:
        type: TEXT
        description: Additional notes about customer relationship
        nullable: true
    relationships:
    - table: NATION
      type: many_to_one
      join_fields:
      - C_NATIONKEY
      - N_NATIONKEY
  ORDERS:
    description: Central record of all customer orders, tracking status, priority, and value
    fields:
      O_ORDERKEY:
        type: NUMBER
        description: Unique order identifier
        nullable: false
        is_key: true
      O_CUSTKEY:
        type: NUMBER
        description: References the customer who placed this order
        nullable: false
        foreign_key: CUSTOMER.C_CUSTKEY
      O_ORDERSTATUS:
        type: TEXT
        description: Current status (F=finished, O=open, P=pending)
        nullable: false
      O_TOTALPRICE:
        type: NUMBER
        description: Total order value including base price, discount, and tax
        nullable: false
      O_ORDERDATE:
        type: DATE
        description: Date when order was placed
        nullable: false
      O_ORDERPRIORITY:
        type: TEXT
        description: Priority level (1-URGENT through 5-LOW)
        nullable: false
      O_CLERK:
        type: TEXT
        description: ID of clerk who processed the order
        nullable: false
      O_SHIPPRIORITY:
        type: NUMBER
        description: Shipping priority indicator
        nullable: false
      O_COMMENT:
        type: TEXT
        description: Additional order processing notes
        nullable: false
    relationships:
    - table: CUSTOMER
      type: many_to_one
      join_fields:
      - O_CUSTKEY
      - C_CUSTKEY
  LINEITEM:
    description: Detailed line items for each order, including product, supplier, and shipping info
    fields:
      L_ORDERKEY:
        type: NUMBER
        description: References the parent order
        nullable: false
        is_key: true
        foreign_key: ORDERS.O_ORDERKEY
      L_PARTKEY:
        type: NUMBER
        description: References the product being ordered
        nullable: false
        foreign_key: PART.P_PARTKEY
      L_SUPPKEY:
        type: NUMBER
        description: References the supplier fulfilling this line item
        nullable: false
        foreign_key: SUPPLIER.S_SUPPKEY
      L_LINENUMBER:
        type: NUMBER
        description: Line item sequence number within the order
        nullable: false
        is_key: true
      L_QUANTITY:
        type: NUMBER
        description: Quantity ordered
        nullable: false
      L_EXTENDEDPRICE:
        type: NUMBER
        description: Line item price before discount and tax
        nullable: false
      L_DISCOUNT:
        type: NUMBER
        description: Discount percentage (0-1)
        nullable: false
      L_TAX:
        type: NUMBER
        description: Tax rate (0-1)
        nullable: false
      L_RETURNFLAG:
        type: TEXT
        description: Return status flag (R=returned, A=accepted)
        nullable: false
      L_LINESTATUS:
        type: TEXT
        description: Line item status (O=open, F=finished)
        nullable: false
      L_SHIPDATE:
        type: DATE
        description: Date line item was shipped
        nullable: false
      L_COMMITDATE:
        type: DATE
        description: Committed delivery date
        nullable: false
      L_RECEIPTDATE:
        type: DATE
        description: Actual receipt date
        nullable: false
      L_SHIPINSTRUCT:
        type: TEXT
        description: Shipping instructions
        nullable: false
      L_SHIPMODE:
        type: TEXT
        description: Shipping mode (REG AIR, MAIL, etc)
        nullable: false
      L_COMMENT:
        type: TEXT
        description: Additional shipping notes
        nullable: false
    relationships:
    - table: ORDERS
      type: many_to_one
      join_fields:
      - L_ORDERKEY
      - O_ORDERKEY
    - table: PART
      type: many_to_one
      join_fields:
      - L_PARTKEY
      - P_PARTKEY
    - table: SUPPLIER
      type: many_to_one
      join_fields:
      - L_SUPPKEY
      - S_SUPPKEY
  PART:
    description: Product catalog with specifications and pricing
    fields:
      P_PARTKEY:
        type: NUMBER
        description: Unique product identifier
        nullable: false
        is_key: true
      P_NAME:
        type: TEXT
        description: Product name/title
        nullable: false
      P_MFGR:
        type: TEXT
        description: Manufacturer name
        nullable: false
      P_BRAND:
        type: TEXT
        description: Product brand
        nullable: false
      P_TYPE:
        type: TEXT
        description: Product category/type
        nullable: false
      P_SIZE:
        type: NUMBER
        description: Product size metric
        nullable: false
      P_CONTAINER:
        type: TEXT
        description: Standard container type
        nullable: false
      P_RETAILPRICE:
        type: NUMBER
        description: Suggested retail price
        nullable: false
      P_COMMENT:
        type: TEXT
        description: Additional product notes
        nullable: true
  SUPPLIER:
    description: Authorized suppliers who fulfill orders
    fields:
      S_SUPPKEY:
        type: NUMBER
        description: Unique supplier identifier
        nullable: false
        is_key: true
      S_NAME:
        type: TEXT
        description: Supplier business name
        nullable: false
      S_ADDRESS:
        type: TEXT
        description: Primary business address
        nullable: false
      S_NATIONKEY:
        type: NUMBER
        description: References supplier's home nation
        nullable: false
        foreign_key: NATION.N_NATIONKEY
      S_PHONE:
        type: TEXT
        description: Primary contact number
        nullable: false
      S_ACCTBAL:
        type: NUMBER
        description: Current account balance
        nullable: false
      S_COMMENT:
        type: TEXT
        description: Additional supplier notes
        nullable: true
    relationships:
    - table: NATION
      type: many_to_one
      join_fields:
      - S_NATIONKEY
      - N_NATIONKEY
  NATION:
    description: Reference table of nations where customers and suppliers are located
    fields:
      N_NATIONKEY:
        type: NUMBER
        description: Unique nation identifier
        nullable: false
        is_key: true
      N_NAME:
        type: TEXT
        description: Nation name
        nullable: false
      N_REGIONKEY:
        type: NUMBER
        description: References the region this nation belongs to
        nullable: false
        foreign_key: REGION.R_REGIONKEY
      N_COMMENT:
        type: TEXT
        description: Additional geographical notes
        nullable: true
    relationships:
    - table: REGION
      type: many_to_one
      join_fields:
      - N_REGIONKEY
      - R_REGIONKEY
  REGION:
    description: Highest level geographical grouping of nations
    fields:
      R_REGIONKEY:
        type: NUMBER
        description: Unique region identifier
        nullable: false
        is_key: true
      R_NAME:
        type: TEXT
        description: Region name (e.g., ASIA, EUROPE)
        nullable: false
      R_COMMENT:
        type: TEXT
        description: Additional regional notes
        nullable: true
