[snowflake]
account = "your-account-here"
user = "your-username"
password = "your-password"
database = "your-database"
warehouse = "your-warehouse"
schema = "your-schema"

[openai]
api_key = "your-openai-key-here"
